### PR TITLE
Play/pause support

### PR DESCRIPTION
**Pull request by ojread**
You have to be careful what you pass to /player/play as it throws a 400 if both context_uri and uris are supplied: https://developer.spotify.com/web-api/start-a-users-playback/

To play a particular track on a particular playlist you have to set the track URI in the offset object.

### CODE REVIEW

**Comment by tkhduracell** [comment]
@ojread While our at it, add next/previous too!

**Comment by tkhduracell** [comment]
@JMPerez review?

**Comment by JMPerez** [comment]
👍

**Comment by JMPerez** [comment]
@ojread Sorry for the late reply. It would be great if you add some unit tests.

**Comment by JMPerez** [comment]
Closing this. This is already covered in https://github.com/thelinmichael/spotify-web-api-node/pull/150.

**Pull request closed without merging**
