### PR TITLE
Use superagent instead of restler - Fixes #56

### LINKED ISSUE #56: Use something other than restler so module is browerify'able
Title says it all, what do you think? I can probably make this change.

### PR DESCRIPTION
**Pull request by SomeoneWeird**
Tried to touch the least amount of code as possible, but some of the tests needed to be changed. Mainly the timeout tests were removed, as I couldn't see a way to actually set a timeout on existing requests, and it didn't look like restler had a default timeout.

### CODE REVIEW

**Comment by JMPerez** [comment]
@SomeoneWeird Wow, awesome work!

This PR looks good to me. I'm only worried that we are relying on an alpha version of [superagent](https://github.com/visionmedia/superagent). Also, its build seems to be failing. I haven't really looked into it, but I would like to feel that superagent is stable and well tested before switching to it.

@thelinmichael what do you think?

**Comment by SomeoneWeird** [comment]
Ah, sure. I didn't even realise npm installed the alpha version. Can easily drop back to 1.x if you think it's going to be an issue.

**Comment by SomeoneWeird** [comment]
What do we wanna do with this? :)

**Comment by JMPerez** [comment]
Hi @SomeoneWeird. It looks like superagent v2.0.0 has been released. Would you mind updating the PR?

Also, I have realised that some tests were removed, specifically the "Should process a failing GET request with a generic error". I wonder whether those tests couldn't be kept with the migration to superagent.

**Comment by SomeoneWeird** [comment]
I've updated the PR to use the latest version of superagent. Superagent doesn't really differentiate errors as much as restler did (arguably it doesn't really matter - it's still an error). That said, I looked through the current testsuite and couldn't see the `Should process a failing GET request with a generic error` test.

**Comment by thelinmichael** [comment]
Awesome work @SomeoneWeird. I believe @JMPerez is referring to https://github.com/thelinmichael/spotify-web-api-node/pull/57/commits/22119bc98b9f1505110a9f9ac191123d3434bd99#diff-a7504c06c761fa6b74b999807fccaa20L72

I'm happy to merge this in.

**Comment by SomeoneWeird** [comment]
Yeah, I can't see that test in the current master branch though (I probably
missed it)

**Comment by thelinmichael** [comment]
Merging this in but restoring the tests. Thanks so much @SomeoneWeird!

**Pull request merged**
