### PR TITLE
added volume and seek methods for user

### PR DESCRIPTION
**Pull request by vanderlin**
https://developer.spotify.com/web-api/console/put-volume/
https://developer.spotify.com/web-api/console/put-seek/

### CODE REVIEW

**Comment by reidpd** [comment]
@JMPerez @thelinmichael Could you please approve this PR? I'd really like to use this functionality in a project I'm currently working on!

**Comment by dado3212** [comment]
Ditto on this for me, would be great to get this in the codebase.

**Comment by dado3212** [comment]
Hey, just wanted to bump this.  Any chance this could get added?

**Comment by theiliad** [comment]
Hey, could someone add this? Thanks :)

**Comment by theiliad** [comment]
A hacky way of adding seek for now until they merge:
For some reason Object.defineProperty doesn't work for me so I'd have to import WebApiRequest!

```js
const SpotifyWebApi = require('spotify-web-api-node'),
      AuthenticationRequest = require('../node_modules/spotify-web-api-node/src/authentication-request'),
      WebApiRequest = require('../node_modules/spotify-web-api-node/src/webapi-request'),
      HttpManager = require('../node_modules/spotify-web-api-node/src/http-manager');

SpotifyWebApi.prototype["seek"] = function(position, callback) {
    const request = WebApiRequest.builder()
        .withPath('/v1/me/player/seek')
        .withHeaders({ 'Content-Type' : 'application/json' })
        .withQueryParameters({
            'position_ms': Math.floor(position)
        })
        .build();

    this._addAccessToken(request, this.getAccessToken());

    const promise = this._performRequest(HttpManager.put, request);

    if (callback) {
        return promise.then((data) => {
            callback(null, data);
        }, (err) => {
            callback(err);
        });
    }

    return promise;
};
```

**Comment by dado3212** [comment]
@thelinmichael @JMPerez just wanted to bump in the new year.

**Comment by kensykora** [comment]
+1 please merge!

**Comment by dado3212** [comment]
That being said, it definitely needs an update, it's pretty out of date from the current version of the repo.

**Comment by robhuzzey** [comment]
Hey, any word on movement on this one? It looks like valid code to me? Anything I can do to help out?

**Comment by jamesemwallis** [comment]
@robhuzzey @dado3212  @kensykora I've just raised https://github.com/thelinmichael/spotify-web-api-node/pull/197/files which contains the requested `device_id` option.

**Comment by JMPerez** [comment]
I'm closing this PR. I have decided to create [a PR](https://github.com/thelinmichael/spotify-web-api-node/pull/203) combining the contributions from several pending PRs that tried to include the functionality but were either missing functionality (eg optional parameters) or tests.

Thank you very much for your contribution and we¡ll try to provide feedback and act on this earlier next time.

**Pull request closed without merging**
